"""Shared utilities package."""

from src.share.config import (
    BASE_DIR,
    BIN_DIR,
    DATA_DIR,
    DEFAULT_CONFIG,
    EMBEDDINGS_DIR,
    LLAMA_BIN_PATH,
    LLM_DIR,
    LOGS_DIR,
    MODELS_DIR,
    QDRANT_BIN_PATH,
    QDRANT_STORAGE_DIR,
    get_backend_gpu_type,
    get_backend_os,
    get_llama_config,
    get_llamacpp_version,
    get_log_level,
    get_os_type,
    get_paths,
    get_qdrant_config,
    get_qdrant_version,
    load_config,
    set_backend_gpu_type,
    set_llamacpp_version,
    set_os_type,
    set_qdrant_version,
)
from src.share.toml_service import TOMLService as TOMLService
from src.share.toml_service import deep_merge as deep_merge

__all__ = [
    "TOMLService",
    "deep_merge",
    "BASE_DIR",
    "BIN_DIR",
    "DATA_DIR",
    "DEFAULT_CONFIG",
    "EMBEDDINGS_DIR",
    "LLAMA_BIN_PATH",
    "LLM_DIR",
    "LOGS_DIR",
    "MODELS_DIR",
    "QDRANT_BIN_PATH",
    "QDRANT_STORAGE_DIR",
    "get_backend_gpu_type",
    "get_backend_os",
    "get_llama_config",
    "get_log_level",
    "get_os_type",
    "get_paths",
    "get_qdrant_config",
    "get_qdrant_version",
    "get_llamacpp_version",
    "load_config",
    "set_backend_gpu_type",
    "set_llamacpp_version",
    "set_os_type",
    "set_qdrant_version",
]
