#!/usr/bin/env python3
"""Project initialization script - creates data structure, config, clones sigma-specification."""

import logging
import shutil
import sys
import tempfile
import time
from pathlib import Path
from typing import Optional

try:
    import git  # GitPython
    from git.exc import GitCommandError
except ImportError:
    print("✗ GitPython not installed. Run: uv add gitpython", file=sys.stderr)
    sys.exit(1)

from src.back.database import DatabaseServiceProtocol
from src.shared.constants import (
    SIGMA_SPEC_REPO,
    SIGMA_SPEC_REF,
    SCHEMA_VERSION,
    DEFAULT_LLAMA_BASE_URL,
    DEFAULT_QDRANT_BASE_URL,
    DEFAULT_QDRANT_COLLECTION,
    DEFAULT_QDRANT_VECTOR_SIZE,
)

# Configure structured logging
logger = logging.getLogger("init_projet")
logger.setLevel(logging.INFO)

# Console handler with structured format
console_handler = logging.StreamHandler(sys.stdout)
console_handler.setLevel(logging.INFO)
formatter = logging.Formatter(
    "%(asctime)s | %(levelname)-8s | %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
)
console_handler.setFormatter(formatter)
logger.addHandler(console_handler)
logger.propagate = False


def log_info(msg: str) -> None:
    """Log info message with checkmark prefix."""
    logger.info(f"✓ {msg}")


def log_warn(msg: str) -> None:
    """Log warning message with warning prefix."""
    logger.warning(f"⚠ {msg}")


def log_error(msg: str) -> None:
    """Log error message with error prefix."""
    logger.error(f"✗ {msg}")


def log_step(msg: str) -> None:
    """Log step message with arrow prefix."""
    logger.info(f"→ {msg}")


SIGMA_SPEC_DIR = Path("data/sigma-specification")
CONFIG_FILE = Path("sigmarag.toml")

DATA_DIRS = [
    "data",
    "data/bin",
    "data/models",
    "data/models/llm",
    "data/models/embeddings",
    "data/duckdb",
    "data/logs",
    "data/pids",
    "data/qdrant_storage",
    "data/temp",
    "data/documents",
    "data/documents/local",
    "data/documents/sigmaref",
    "data/github",
    "data/rag_cache",
]


def _generate_default_toml() -> str:
    """Generate default TOML from shared constants to keep in sync."""
    lines = [
        "# SigmaHQ RAG Configuration",
        "# Generated by init_projet.py - DO NOT EDIT MANUALLY (use the API)",
        "",
        "[services.llama]",
        f'base_url = "{DEFAULT_LLAMA_BASE_URL}"',
        "manage_internally = false",
        "",
        "[services.qdrant]",
        f'base_url = "{DEFAULT_QDRANT_BASE_URL}"',
        "manage_internally = false",
        f'collection_name = "{DEFAULT_QDRANT_COLLECTION}"',
        f"vector_size = {DEFAULT_QDRANT_VECTOR_SIZE}",
        "",
        "[logging]",
        'level = "INFO"',
        'log_max_size = "10M"',
        "log_max_file = 5",
        "clean_at_startup = false",
        "",
        "[rag]",
        "enable_rich_chunks = true",
        "",
    ]
    return "\n".join(lines)


DEFAULT_TOML = _generate_default_toml()


def create_data_structure() -> None:
    """Create all required data directories."""
    for d in DATA_DIRS:
        try:
            Path(d).mkdir(parents=True, exist_ok=True)
        except (PermissionError, OSError) as e:
            log_error(f"Failed to create directory {d}: {e}")
            sys.exit(1)
    log_info("Data directory structure created")


def create_config_file() -> None:
    """Create sigmarag.toml at project root (no [backend] section)."""
    if not CONFIG_FILE.exists():
        CONFIG_FILE.write_text(DEFAULT_TOML, encoding="utf-8")
        log_info(f"Created {CONFIG_FILE}")
    else:
        log_info(f"{CONFIG_FILE} already exists")


def clone_or_update_sigma_spec() -> None:
    """Clone or update sigma-specification repository."""
    if SIGMA_SPEC_DIR.exists():
        log_step("Updating existing sigma-specification...")
        try:
            repo = git.Repo(SIGMA_SPEC_DIR)
            if repo.is_dirty():
                log_warn("Working tree has uncommitted changes, stashing...")
                repo.git.stash()
            repo.remotes.origin.pull()
            log_info("sigma-specification updated")
        except GitCommandError as e:
            log_warn(f"Pull failed: {e}. Attempting fetch + hard reset...")
            try:
                repo = git.Repo(SIGMA_SPEC_DIR)
                repo.remotes.origin.fetch()
                repo.git.reset("--hard", f"origin/{SIGMA_SPEC_REF}")
                log_info("sigma-specification updated via hard reset")
            except GitCommandError as e2:
                log_error(f"Failed to update sigma-specification: {e2}")
                sys.exit(1)
    else:
        log_step("Cloning sigma-specification...")
        SIGMA_SPEC_DIR.parent.mkdir(parents=True, exist_ok=True)
        temp_dir = None
        max_retries = 3
        for attempt in range(1, max_retries + 1):
            try:
                # Atomic clone: clone to temp directory first, then move
                with tempfile.TemporaryDirectory(prefix="sigma-spec-") as tmp:
                    temp_dir = Path(tmp) / "sigma-specification"
                    git.Repo.clone_from(SIGMA_SPEC_REPO, temp_dir, branch=SIGMA_SPEC_REF)
                    # Move atomically (on same filesystem)
                    if SIGMA_SPEC_DIR.exists():
                        shutil.rmtree(SIGMA_SPEC_DIR)
                    shutil.move(str(temp_dir), str(SIGMA_SPEC_DIR))
                log_info("sigma-specification cloned")
                break
            except GitCommandError as e:
                if attempt == max_retries:
                    log_error(
                        f"Failed to clone sigma-specification after {max_retries} attempts: {e}"
                    )
                    sys.exit(1)
                log_warn(f"Clone attempt {attempt}/{max_retries} failed: {e}. Retrying...")
                time.sleep(2 * attempt)  # Exponential backoff
            except OSError as e:
                log_error(f"Failed to move cloned repository: {e}")
                sys.exit(1)


EXPECTED_TABLES = frozenset(
    {
        "config",
        "embedding_config",
        "system_prompts",
        "models",
        "doc_registry",
        "worker_state",
        "git_metadata",
        "git_selected_dirs",
        "sigma_spec",
        "doc_error",
    }
)


def initialize_database(db_service: Optional[DatabaseServiceProtocol] = None) -> None:
    """Initialize DuckDB schema and verify tables."""
    # Import here to avoid circular imports
    from src.back.database import DatabaseService

    db = db_service or DatabaseService()
    db.initialize()

    tables = frozenset(db.get_tables())
    missing = EXPECTED_TABLES - tables
    if missing:
        log_error(f"Missing tables after init: {sorted(missing)}")
        db.close()
        sys.exit(1)

    # Set schema version in config table
    try:
        db.set_config("schema_version", SCHEMA_VERSION)
        log_info(f"Schema version set to {SCHEMA_VERSION}")
    except Exception as e:
        log_error(f"Failed to set schema version: {e}")
        db.close()
        sys.exit(1)

    log_info(f"DuckDB initialized: {len(tables)} tables verified")
    log_info(f"  embedding_config: {db.get_table_count('embedding_config')} rows")
    log_info(f"  system_prompts:   {db.get_table_count('system_prompts')} rows")
    log_info(f"  config:           {db.get_table_count('config')} rows")
    db.close()


def main() -> None:
    logger.info("=" * 50)
    logger.info("SigmaHQ RAG - Project Initialization")
    logger.info("=" * 50)

    create_data_structure()
    create_config_file()
    clone_or_update_sigma_spec()
    initialize_database()

    logger.info("=" * 50)
    log_info("Initialization complete!")
    logger.info("  Run 'uv run main.py' to start the server")
    logger.info("=" * 50)


if __name__ == "__main__":
    main()
