#!/usr/bin/env python3
"""Project initialization script - creates data structure, config, clones sigma-specification."""

import shutil
import sys
import tempfile
from pathlib import Path
from typing import Optional, Protocol

try:
    import git  # GitPython
    from git.exc import GitCommandError
except ImportError:
    print("✗ GitPython not installed. Run: uv add gitpython", file=sys.stderr)
    sys.exit(1)

SIGMA_SPEC_REPO = "https://github.com/SigmaHQ/sigma-specification"
SIGMA_SPEC_DIR = Path("data/sigma-specification")
CONFIG_FILE = Path("sigmarag.toml")

DATA_DIRS = [
    "data",
    "data/bin",
    "data/models",
    "data/models/llm",
    "data/models/embeddings",
    "data/duckdb",
    "data/logs",
    "data/pids",
    "data/qdrant_storage",
    "data/temp",
    "data/documents",
    "data/documents/local",
    "data/documents/sigmaref",
    "data/github",
    "data/rag_cache",
]


def _generate_default_toml() -> str:
    """Generate default TOML from Config defaults to keep in sync."""
    # Use the same defaults as Config class to ensure consistency
    lines = [
        "# SigmaHQ RAG Configuration",
        "# Generated by init_projet.py - DO NOT EDIT MANUALLY (use the API)",
        "",
        "[services.llama]",
        'base_url = "http://127.0.0.1:8080"',
        "manage_internally = false",
        "",
        "[services.qdrant]",
        'base_url = "http://127.0.0.1:6333"',
        "manage_internally = false",
        "",
        "[logging]",
        'level = "INFO"',
        'log_max_size = "10M"',
        "log_max_file = 5",
        "clean_at_startup = false",
        "",
        "[rag]",
        "enable_rich_chunks = true",
        "",
    ]
    return "\n".join(lines)


DEFAULT_TOML = _generate_default_toml()


def create_data_structure() -> None:
    """Create all required data directories."""
    for d in DATA_DIRS:
        try:
            Path(d).mkdir(parents=True, exist_ok=True)
        except (PermissionError, OSError) as e:
            print(f"✗ ERROR: Failed to create directory {d}: {e}", file=sys.stderr)
            sys.exit(1)
    print("✓ Data directory structure created")


def create_config_file() -> None:
    """Create sigmarag.toml at project root (no [backend] section)."""
    if not CONFIG_FILE.exists():
        CONFIG_FILE.write_text(DEFAULT_TOML, encoding="utf-8")
        print(f"✓ Created {CONFIG_FILE}")
    else:
        print(f"✓ {CONFIG_FILE} already exists")


def clone_or_update_sigma_spec() -> None:
    """Clone or update sigma-specification repository."""
    if SIGMA_SPEC_DIR.exists():
        print("→ Updating existing sigma-specification...")
        try:
            repo = git.Repo(SIGMA_SPEC_DIR)
            if repo.is_dirty():
                print("  ⚠ Working tree has uncommitted changes, stashing...")
                repo.git.stash()
            repo.remotes.origin.pull()
            print("✓ sigma-specification updated")
        except GitCommandError as e:
            print(f"  ⚠ Pull failed: {e}. Attempting fetch + hard reset...")
            try:
                repo = git.Repo(SIGMA_SPEC_DIR)
                repo.remotes.origin.fetch()
                repo.git.reset("--hard", "origin/main")
                print("✓ sigma-specification updated via hard reset")
            except GitCommandError as e2:
                print(f"✗ ERROR: Failed to update sigma-specification: {e2}", file=sys.stderr)
                sys.exit(1)
    else:
        print("→ Cloning sigma-specification...")
        SIGMA_SPEC_DIR.parent.mkdir(parents=True, exist_ok=True)
        temp_dir = None
        try:
            # Atomic clone: clone to temp directory first, then move
            with tempfile.TemporaryDirectory(prefix="sigma-spec-") as tmp:
                temp_dir = Path(tmp) / "sigma-specification"
                git.Repo.clone_from(SIGMA_SPEC_REPO, temp_dir)
                # Move atomically (on same filesystem)
                if SIGMA_SPEC_DIR.exists():
                    shutil.rmtree(SIGMA_SPEC_DIR)
                shutil.move(str(temp_dir), str(SIGMA_SPEC_DIR))
            print("✓ sigma-specification cloned")
        except GitCommandError as e:
            print(f"✗ ERROR: Failed to clone sigma-specification: {e}", file=sys.stderr)
            sys.exit(1)
        except OSError as e:
            print(f"✗ ERROR: Failed to move cloned repository: {e}", file=sys.stderr)
            sys.exit(1)


class DatabaseServiceProtocol(Protocol):
    """Protocol for database service to enable dependency injection in tests."""

    def initialize(self) -> None: ...
    def get_tables(self) -> list[str]: ...
    def get_table_count(self, table_name: str) -> int: ...
    def set_config(self, key: str, value: int) -> None: ...
    def close(self) -> None: ...


SCHEMA_VERSION = 1


def initialize_database(db_service: Optional[DatabaseServiceProtocol] = None) -> None:
    """Initialize DuckDB schema and verify tables."""
    # Import here to avoid circular imports
    from src.back.database import DatabaseService

    expected_tables = frozenset(
        {
            "config",
            "embedding_config",
            "system_prompts",
            "models",
            "doc_registry",
            "worker_state",
            "git_metadata",
            "git_selected_dirs",
            "sigma_spec",
            "doc_error",
        }
    )

    db = db_service or DatabaseService()
    db.initialize()

    tables = frozenset(db.get_tables())
    missing = expected_tables - tables
    if missing:
        print(f"✗ ERROR: Missing tables after init: {sorted(missing)}", file=sys.stderr)
        db.close()
        sys.exit(1)

    # Set schema version in config table
    try:
        db.set_config("schema_version", SCHEMA_VERSION)
        print(f"✓ Schema version set to {SCHEMA_VERSION}")
    except Exception as e:
        print(f"✗ ERROR: Failed to set schema version: {e}", file=sys.stderr)
        db.close()
        sys.exit(1)

    print(f"✓ DuckDB initialized: {len(tables)} tables verified")
    print(f"  embedding_config: {db.get_table_count('embedding_config')} rows")
    print(f"  system_prompts:   {db.get_table_count('system_prompts')} rows")
    print(f"  config:           {db.get_table_count('config')} rows")
    db.close()


def main() -> None:
    print("=" * 50)
    print("SigmaHQ RAG - Project Initialization")
    print("=" * 50)

    create_data_structure()
    create_config_file()
    clone_or_update_sigma_spec()
    initialize_database()

    print("=" * 50)
    print("✓ Initialization complete!")
    print("  Run 'uv run main.py' to start the server")
    print("=" * 50)


if __name__ == "__main__":
    main()
