#!/usr/bin/env python3
"""SigmaHQ RAG Setup — Linux-installer style TUI with full-screen layout and keyboard navigation."""

from __future__ import annotations

import shutil
import sys
import tempfile
import time
from pathlib import Path
from typing import Optional, Protocol, runtime_checkable

import git
from git.exc import GitCommandError
from rich.console import Console
from rich.panel import Panel
from rich.progress import (
    BarColumn,
    Progress,
    SpinnerColumn,
    TaskProgressColumn,
    TextColumn,
    TimeElapsedColumn,
)
from rich.prompt import Confirm, IntPrompt, Prompt
from rich.text import Text
from src.workers.enums import WorkerName, WorkerStatus

console = Console()

# ── Constants ──

SIGMA_SPEC_DIR = Path("data/sigma-specification")
CONFIG_FILE = Path("sigmarag.toml")

DATA_DIRS = [
    "data",
    "data/bin",
    "data/models",
    "data/models/llm",
    "data/models/embeddings",
    "data/duckdb",
    "data/logs",
    "data/pids",
    "data/qdrant_storage",
    "data/temp",
    "data/documents",
    "data/documents/local",
    "data/documents/sigmaref",
    "data/github",
    "data/rag_cache",
]

EXPECTED_TABLES = frozenset(
    {
        "config",
        "embedding_config",
        "system_prompts",
        "models",
        "doc_registry",
        "worker_state",
        "git_metadata",
        "git_selected_dirs",
        "sigma_spec",
        "doc_error",
        "release_cache",
    }
)

SCHEMA_VERSION = 1  # Re-export for test compatibility


@runtime_checkable
class DatabaseServiceProtocol(Protocol):
    """Protocol for database service injection in tests."""

    def initialize(self) -> None: ...
    def get_tables(self) -> list[str]: ...
    def get_table_count(self) -> int: ...
    def set_config(self, key: str, value: object) -> None: ...


# ── Core operations (unchanged signatures for test compatibility) ──


def _generate_default_toml() -> str:
    from src.config.constants import (
        DEFAULT_LLAMA_BASE_URL,
        DEFAULT_QDRANT_BASE_URL,
        DEFAULT_QDRANT_COLLECTION,
        DEFAULT_QDRANT_VECTOR_SIZE,
    )

    lines = [
        "# SigmaHQ RAG Configuration",
        "# Generated by setup.py - DO NOT EDIT MANUALLY (use the API)",
        "",
        "[services.llama]",
        f'base_url = "{DEFAULT_LLAMA_BASE_URL}"',
        "manage_internally = false",
        "",
        "[services.qdrant]",
        f'base_url = "{DEFAULT_QDRANT_BASE_URL}"',
        "manage_internally = false",
        f'collection_name = "{DEFAULT_QDRANT_COLLECTION}"',
        f"vector_size = {DEFAULT_QDRANT_VECTOR_SIZE}",
        "",
        "[logging]",
        'level = "INFO"',
        'log_max_size = "10M"',
        "log_max_file = 5",
        "clean_at_startup = false",
        "",
        "[Hardware]",
        'os = "windows"',
        'gpu = "vulkan"',
        "",
    ]
    return "\n".join(lines)


DEFAULT_TOML = _generate_default_toml()


def create_data_structure() -> None:
    for d in DATA_DIRS:
        try:
            Path(d).mkdir(parents=True, exist_ok=True)
        except (PermissionError, OSError) as e:
            console.print(f"[red]✗[/] Failed to create directory {d}: {e}")
            sys.exit(1)


def create_config_file(content: str | None = None) -> None:
    if not CONFIG_FILE.exists():
        CONFIG_FILE.write_text(content or DEFAULT_TOML, encoding="utf-8")


def clone_or_update_sigma_spec() -> None:
    from src.config.constants import SIGMA_SPEC_REF, SIGMA_SPEC_REPO

    if SIGMA_SPEC_DIR.exists():
        try:
            repo = git.Repo(SIGMA_SPEC_DIR)
            if repo.is_dirty():
                repo.git.stash()
            repo.remotes.origin.pull()
        except GitCommandError:
            try:
                repo = git.Repo(SIGMA_SPEC_DIR)
                repo.remotes.origin.fetch()
                repo.git.reset("--hard", f"origin/{SIGMA_SPEC_REF}")
            except GitCommandError as e2:
                console.print(f"[red]✗[/] Failed to update sigma-specification: {e2}")
                sys.exit(1)
    else:
        SIGMA_SPEC_DIR.parent.mkdir(parents=True, exist_ok=True)
        max_retries = 3
        for attempt in range(1, max_retries + 1):
            try:
                with tempfile.TemporaryDirectory(prefix="sigma-spec-") as tmp:
                    temp_dir = Path(tmp) / "sigma-specification"
                    git.Repo.clone_from(SIGMA_SPEC_REPO, temp_dir, branch=SIGMA_SPEC_REF)
                    if SIGMA_SPEC_DIR.exists():
                        shutil.rmtree(SIGMA_SPEC_DIR)
                    shutil.move(str(temp_dir), str(SIGMA_SPEC_DIR))
                break
            except GitCommandError as e:
                if attempt == max_retries:
                    console.print(
                        f"[red]✗[/] Failed to clone sigma-specification "
                        f"after {max_retries} attempts: {e}"
                    )
                    sys.exit(1)
                time.sleep(2 * attempt)
            except OSError as e:
                console.print(f"[red]✗[/] Failed to move cloned repository: {e}")
                sys.exit(1)


def initialize_database(db_service: Optional["DatabaseServiceProtocol"] = None) -> None:
    from src.infrastructure.database import DatabaseService

    db = db_service or DatabaseService()
    db.initialize()

    tables = frozenset(db.get_tables())
    missing = EXPECTED_TABLES - tables
    if missing:
        console.print(f"[red]✗[/] Missing tables after init: {sorted(missing)}")
        sys.exit(1)

    from src.config.constants import SCHEMA_VERSION

    try:
        db.set_config("schema_version", SCHEMA_VERSION)
    except Exception as e:
        console.print(f"[red]✗[/] Failed to set schema version: {e}")
        sys.exit(1)


def run_initial_workers() -> None:
    from src.config.settings import EMBEDDINGS_DIR, LLM_DIR
    from src.workers.processor import TaskDispatcher

    dispatcher: object | None = None
    try:
        dispatcher = TaskDispatcher(poll_interval=1, max_workers=4)
        dispatcher.start()

        dispatcher.ask_for_worker(
            WorkerName.MODEL_SYNC,
            llm_dir=str(LLM_DIR),
            embeddings_dir=str(EMBEDDINGS_DIR),
        )
        dispatcher.ask_for_worker(WorkerName.LOCAL_REPO_SYNC)

        _wait_for_initial_workers(dispatcher)
    except KeyboardInterrupt:
        console.print("\n[red]✗[/] Initialization interrupted by user.")
        sys.exit(130)
    finally:
        if dispatcher is not None:
            dispatcher.stop()

    _sync_model_registry_to_db()


def _wait_for_initial_workers(dispatcher: object) -> None:
    max_wait = 300
    poll_interval = 2
    start_time = time.time()

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        TimeElapsedColumn(),
        console=console,
    ) as progress:
        model_task = progress.add_task("[yellow]ModelSyncWorker[/]", total=None)
        repo_task = progress.add_task("[yellow]LocalRepoSyncWorker[/]", total=None)

        while time.time() - start_time < max_wait:
            model_progress_data = dispatcher.get_worker_progress(WorkerName.MODEL_SYNC.value)
            repo_progress_data = dispatcher.get_worker_progress(WorkerName.LOCAL_REPO_SYNC.value)

            model_status = model_progress_data.get("status") if model_progress_data else None
            repo_status = repo_progress_data.get("status") if repo_progress_data else None

            errors: list[str] = []
            if model_status == WorkerStatus.ERROR.value:
                errors.append("ModelSyncWorker ended with ERROR")
            if repo_status == WorkerStatus.ERROR.value:
                errors.append("LocalRepoSyncWorker ended with ERROR")
            if errors:
                for msg in errors:
                    console.print(f"[red]✗[/] {msg}")
                sys.exit(1)

            if model_status == WorkerStatus.IDLE.value:
                progress.update(model_task, completed=100, total=100)
            if repo_status == WorkerStatus.IDLE.value:
                progress.update(repo_task, completed=100, total=100)
            if model_status == WorkerStatus.IDLE.value and repo_status == WorkerStatus.IDLE.value:
                return

            time.sleep(poll_interval)

        console.print(f"[red]✗[/] Timeout ({max_wait}s) waiting for initial workers")
        sys.exit(1)


def _sync_model_registry_to_db() -> None:
    try:
        from src.config.settings import EMBEDDINGS_DIR, LLM_DIR
        from src.infrastructure.database import DatabaseService
        from src.back.models.registry import UnifiedRegistry

        db = DatabaseService.get_instance()
        reg = UnifiedRegistry.get_instance()
        reg.sync_llm_folder(LLM_DIR, db)
        reg.sync_embeddings_folder(EMBEDDINGS_DIR, db)
    except ImportError as e:
        console.print(f"[yellow]⚠[/] Model registry sync skipped: {e}")
    except Exception as e:
        console.print(f"[yellow]⚠[/] Model registry sync failed: {e}")


# ── TUI helpers ──


def _generate_custom_toml(cfg: dict) -> str:
    from src.config.constants import (
        DEFAULT_LLAMA_BASE_URL,
        DEFAULT_QDRANT_BASE_URL,
        DEFAULT_QDRANT_COLLECTION,
        DEFAULT_QDRANT_VECTOR_SIZE,
    )
    from src.config.constants import (
        TOML_CONFIG_KEYS,
        TOML_SECTIONS,
    )

    # Validate: any new config section added to constants.py must appear here.
    assert TOML_SECTIONS == frozenset(
        {
            "services.llama",
            "services.qdrant",
            "logging",
            "Hardware",
        }
    ), "TOML_SECTIONS drift — _generate_custom_toml() is missing a section"
    assert TOML_CONFIG_KEYS.get("services.llama") == ["base_url", "manage_internally"], (
        "TOML_CONFIG_KEYS.dr - services.llama key mismatch"
    )
    assert TOML_CONFIG_KEYS.get("services.qdrant") == [
        "base_url",
        "manage_internally",
        "collection_name",
        "vector_size",
    ], "TOML_CONFIG_KEYS.dr - services.qdrant key mismatch"
    assert TOML_CONFIG_KEYS.get("logging") == [
        "level",
        "log_max_size",
        "log_max_file",
        "clean_at_startup",
    ], "TOML_CONFIG_KEYS.dr - logging key mismatch"
    assert TOML_CONFIG_KEYS.get("Hardware") == ["os", "gpu"], (
        "TOML_CONFIG_KEYS.dr - Hardware key mismatch"
    )

    gpu_val = cfg.get("gpu", "vulkan")
    os_val = cfg.get("os", "windows")
    lines = [
        "# SigmaHQ RAG Configuration",
        "# Generated by setup.py",
        "",
        "[services.llama]",
        f'base_url = "{cfg.get("llama_url", DEFAULT_LLAMA_BASE_URL)}"',
        f"manage_internally = {str(cfg.get('llama_internal', False)).lower()}",
        "",
        "[services.qdrant]",
        f'base_url = "{cfg.get("qdrant_url", DEFAULT_QDRANT_BASE_URL)}"',
        f"manage_internally = {str(cfg.get('qdrant_internal', False)).lower()}",
        f'collection_name = "{cfg.get("qdrant_collection", DEFAULT_QDRANT_COLLECTION)}"',
        f"vector_size = {cfg.get('qdrant_vector_size', DEFAULT_QDRANT_VECTOR_SIZE)}",
        "",
        "[logging]",
        f'level = "{cfg.get("log_level", "INFO")}"',
        'log_max_size = "10M"',
        "log_max_file = 5",
        "clean_at_startup = false",
        "",
        "[Hardware]",
        f'os = "{os_val}"',
        f'gpu = "{gpu_val}"',
        "",
    ]
    return "\n".join(lines)


# ── Full-screen installer TUI ──

STEPS = [
    ("LLM Service", "llama_url", "llama_internal"),
    ("Qdrant Service", "qdrant_url", "qdrant_internal", "qdrant_collection", "qdrant_vector_size"),
    ("Logging", "log_level"),
    ("Hardware", "os", "gpu"),
]

STEP_LABELS = [
    "1 LLM",
    "2 Qdrant",
    "3 Logging",
    "4 Hardware",
    "5 Review",
]


def _render_step_bar(current_step: int, total_steps: int) -> Panel:
    segments = []
    for i in range(total_steps):
        if i < current_step:
            segments.append(Text("✓", style="green"))
        elif i == current_step:
            segments.append(Text("►", style="cyan bold"))
        else:
            segments.append(Text("○", style="dim"))

    bar = " ".join(segments)
    return Panel(
        bar,
        title="[dim]Steps[/]",
        title_align="left",
        border_style="cyan",
        padding=(0, 1),
    )


def _render_step_content(title: str, content: str, current_step: int) -> Panel:
    return Panel(
        content,
        title=f"[bold cyan]{title}[/]",
        border_style="blue",
    )


def _render_left_panel(current_step: int) -> Panel:
    from src.config.constants import (
        DEFAULT_LLAMA_BASE_URL,
        DEFAULT_QDRANT_BASE_URL,
        DEFAULT_QDRANT_COLLECTION,
        DEFAULT_QDRANT_VECTOR_SIZE,
    )

    lines = [
        "[bold]SigmaHQ RAG[/] — Local RAG for Sigma rules",
        "",
        "[dim]Navigation:[/]",
        "  ↑↓  Move between fields",
        "  Tab Next field",
        "  Enter Confirm selection",
        "",
        "[dim]Quick defaults:[/]",
        "  LLM:     " + DEFAULT_LLAMA_BASE_URL,
        "  Qdrant:  " + DEFAULT_QDRANT_BASE_URL,
        f"  Collection: {DEFAULT_QDRANT_COLLECTION}",
        f"  Vector size: {DEFAULT_QDRANT_VECTOR_SIZE}",
        "",
        "[dim]Keyboard:[/]",
        "  Ctrl+C  Abort",
        "  Space   Toggle checkbox",
    ]

    return Panel(
        "\n".join(lines),
        title="[dim]Help[/]",
        border_style="dim",
        padding=(1, 2),
    )


def _render_right_panel(current_step: int, cfg: dict, show_preview: bool = False) -> Panel:
    from src.config.constants import (
        DEFAULT_LLAMA_BASE_URL,
        DEFAULT_QDRANT_BASE_URL,
        DEFAULT_LLAMA_MANAGE,
        DEFAULT_QDRANT_MANAGE,
        DEFAULT_QDRANT_COLLECTION,
        DEFAULT_QDRANT_VECTOR_SIZE,
    )

    if show_preview:
        preview_lines = []
        preview_lines.append("[bold yellow]Configuration Preview[/]")
        preview_lines.append("")
        preview_lines.append(f"LLM URL:          {cfg.get('llama_url', DEFAULT_LLAMA_BASE_URL)}")
        preview_lines.append(f"LLM Internal:     {cfg.get('llama_internal', DEFAULT_LLAMA_MANAGE)}")
        preview_lines.append(f"Qdrant URL:       {cfg.get('qdrant_url', DEFAULT_QDRANT_BASE_URL)}")
        preview_lines.append(
            f"Qdrant Internal:  {cfg.get('qdrant_internal', DEFAULT_QDRANT_MANAGE)}"
        )
        preview_lines.append(
            f"Collection:       {cfg.get('qdrant_collection', DEFAULT_QDRANT_COLLECTION)}"
        )
        preview_lines.append(
            f"Vector Size:      {cfg.get('qdrant_vector_size', DEFAULT_QDRANT_VECTOR_SIZE)}"
        )
        preview_lines.append(f"Log Level:        {cfg.get('log_level', 'INFO')}")
        preview_lines.append(f"OS:               {cfg.get('os', 'Windows')}")
        preview_lines.append(f"GPU:              {cfg.get('gpu', 'vulkan')}")
        preview_lines.append("")
        preview_lines.append("[bold green]✓[/] Ready to initialize!")
        preview_lines.append("")
        preview_lines.append("[dim]Press Enter to start[/]")
        content = "\n".join(preview_lines)
    else:
        content = _render_current_step_content(current_step, cfg)

    return Panel(
        content,
        title=f"[bold]Step {current_step + 1}/5[/]",
        border_style="blue",
    )


def _render_current_step_content(step: int, cfg: dict) -> str:
    from src.config.constants import (
        DEFAULT_LLAMA_BASE_URL,
        DEFAULT_LLAMA_MANAGE,
        DEFAULT_QDRANT_BASE_URL,
        DEFAULT_QDRANT_MANAGE,
        DEFAULT_QDRANT_COLLECTION,
        DEFAULT_QDRANT_VECTOR_SIZE,
    )

    if step == 0:
        return (
            "[bold]Step 1: LLM Service[/]\n"
            "\n"
            f"Base URL: [cyan]{cfg.get('llama_url', DEFAULT_LLAMA_BASE_URL)}[/]\n"
            f"Manage internally: [{'green' if cfg.get('llama_internal', DEFAULT_LLAMA_MANAGE) else 'red'}] {cfg.get('llama_internal', DEFAULT_LLAMA_MANAGE)}\n"
            "\n"
            "[dim]Configure your llama.cpp-compatible server.[/]"
        )
    elif step == 1:
        return (
            "[bold]Step 2: Qdrant Service[/]\n"
            "\n"
            f"Base URL: [cyan]{cfg.get('qdrant_url', DEFAULT_QDRANT_BASE_URL)}[/]\n"
            f"Manage internally: [{'green' if cfg.get('qdrant_internal', DEFAULT_QDRANT_MANAGE) else 'red'}] {cfg.get('qdrant_internal', DEFAULT_QDRANT_MANAGE)}\n"
            f"Collection: [cyan]{cfg.get('qdrant_collection', DEFAULT_QDRANT_COLLECTION)}[/]\n"
            f"Vector size: [cyan]{cfg.get('qdrant_vector_size', DEFAULT_QDRANT_VECTOR_SIZE)}[/]\n"
            "\n"
            "[dim]Configure the vector database.[/]"
        )
    elif step == 2:
        return (
            "[bold]Step 3: Logging[/]\n"
            "\n"
            f"Log level: [cyan]{cfg.get('log_level', 'INFO')}[/]\n"
            "\n"
            "[dim]Set the logging verbosity.[/]"
        )
    elif step == 3:
        return (
            "[bold]Step 4: Hardware[/]\n"
            "\n"
            f"OS: [cyan]{cfg.get('os', 'windows')}[/]\n"
            f"GPU: [cyan]{cfg.get('gpu', 'vulkan')}[/]\n"
            "\n"
            "[dim]OS and GPU configuration.[/]"
        )
    return "Configuration"


def _interactive_tui() -> dict:
    """Full-screen installer TUI with step-by-step navigation."""
    from src.config.constants import (
        DEFAULT_LLAMA_BASE_URL,
        DEFAULT_LLAMA_MANAGE,
        DEFAULT_QDRANT_BASE_URL,
        DEFAULT_QDRANT_MANAGE,
        DEFAULT_QDRANT_COLLECTION,
        DEFAULT_QDRANT_VECTOR_SIZE,
    )

    cfg: dict = {
        "llama_url": DEFAULT_LLAMA_BASE_URL,
        "llama_internal": DEFAULT_LLAMA_MANAGE,
        "qdrant_url": DEFAULT_QDRANT_BASE_URL,
        "qdrant_internal": DEFAULT_QDRANT_MANAGE,
        "qdrant_collection": DEFAULT_QDRANT_COLLECTION,
        "qdrant_vector_size": DEFAULT_QDRANT_VECTOR_SIZE,
        "log_level": "INFO",
        "os": "windows",
        "gpu": "vulkan",
    }

    console.clear()
    console.print(
        Panel(
            "[bold cyan]SigmaHQ RAG[/] — Setup\n"
            "[dim]Use ↑↓ to navigate, Tab for next field, Space to toggle, Enter to confirm[/]",
            border_style="cyan",
            padding=(1, 2),
        )
    )

    current_step = 0
    current_field = 0

    while True:
        console.clear()
        console.print(_render_step_bar(current_step, len(STEPS)))
        console.print()

        if current_step == len(STEPS):
            # Review step
            console.print(_render_right_panel(current_step, cfg, show_preview=True))
            decision = Prompt.ask(
                "\n[bold]Proceed with initialization?[/]", default=True, choices=["y", "n"]
            )
            if decision == "n":
                console.print("[yellow]Aborted by user.[/]")
                sys.exit(0)
            break

        step_fields = STEPS[current_step]
        step_name = step_fields[0]

        if current_field == 0:
            # First field of this step
            if step_name == "LLM Service":
                cfg["llama_url"] = Prompt.ask("LLM Base URL", default=cfg["llama_url"])
            elif step_name == "Qdrant Service":
                cfg["qdrant_url"] = Prompt.ask("Qdrant Base URL", default=cfg["qdrant_url"])
            elif step_name == "Logging":
                cfg["log_level"] = Prompt.ask(
                    "Log level",
                    choices=["DEBUG", "INFO", "WARNING", "ERROR"],
                    default=cfg["log_level"],
                )
            elif step_name == "Hardware":
                cfg["os"] = Prompt.ask(
                    "Operating system",
                    choices=["windows", "linux", "macos"],
                    default=cfg["os"],
                )

        elif current_field == 1:
            if step_name == "LLM Service":
                cfg["llama_internal"] = Confirm.ask(
                    "Manage internally?", default=cfg["llama_internal"]
                )
            elif step_name == "Qdrant Service":
                cfg["qdrant_internal"] = Confirm.ask(
                    "Manage internally?", default=cfg["qdrant_internal"]
                )
            elif step_name == "Hardware":
                cfg["gpu"] = Prompt.ask(
                    "GPU acceleration",
                    choices=["cpu", "vulkan", "cuda"],
                    default=cfg["gpu"],
                )

        elif current_field == 2:
            if step_name == "Qdrant Service":
                cfg["qdrant_collection"] = Prompt.ask(
                    "Collection name", default=cfg["qdrant_collection"]
                )

        elif current_field == 3:
            if step_name == "Qdrant Service":
                cfg["qdrant_vector_size"] = IntPrompt.ask(
                    "Vector size", default=cfg["qdrant_vector_size"]
                )

        current_field += 1

        if current_field >= len(step_fields):
            current_field = 0
            current_step += 1

    return cfg


def _print_config_summary(cfg: dict) -> None:
    console.print()
    console.print(
        Panel.fit(
            f"[bold]LLM URL:[/]\t\t{cfg.get('llama_url', '')}\n"
            f"[bold]LLM Internal:[/]\t{cfg.get('llama_internal', False)}\n"
            f"[bold]Qdrant URL:[/]\t\t{cfg.get('qdrant_url', '')}\n"
            f"[bold]Qdrant Internal:[/]\t{cfg.get('qdrant_internal', False)}\n"
            f"[bold]Collection:[/]\t\t{cfg.get('qdrant_collection', '')}\n"
            f"[bold]Vector Size:[/]\t\t{cfg.get('qdrant_vector_size', 0)}\n"
            f"[bold]Log Level:[/]\t\t{cfg.get('log_level', '')}\n"
            f"[bold]OS:[/]\t\t\t{cfg.get('os', '')}\n"
            f"[bold]GPU:[/]\t\t\t{cfg.get('gpu', '')}",
            title="[bold]Configuration Summary[/]",
            border_style="green",
        )
    )


# ── Entry points ──


def run_tui() -> None:
    """Full TUI flow."""
    console.print()
    console.print(
        Panel.fit(
            "[bold cyan]SigmaHQ RAG[/] — Local RAG system for Sigma rules\n\n"
            "[dim]This wizard will help you initialize the project:\n"
            "  • Create data directories\n"
            "  • Configure services (LLM, Qdrant)\n"
            "  • Clone the Sigma specification repository\n"
            "  • Initialize the DuckDB database\n"
            "  • Sync models and reference data[/]",
            title="[bold]Project Initialization[/]",
            border_style="cyan",
        )
    )
    console.print()

    cfg = _interactive_tui()

    _print_config_summary(cfg)

    console.print()
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        TimeElapsedColumn(),
        console=console,
    ) as progress:
        task_dirs = progress.add_task("[cyan]Creating data directories...[/]", total=None)
        create_data_structure()
        progress.update(task_dirs, completed=100, total=100)

        task_config = progress.add_task("[cyan]Writing configuration...[/]", total=None)
        toml_content = _generate_custom_toml(cfg)
        create_config_file(content=toml_content)
        progress.update(task_config, completed=100, total=100)

        task_sigma = progress.add_task("[cyan]Cloning sigma-specification...[/]", total=None)
        clone_or_update_sigma_spec()
        progress.update(task_sigma, completed=100, total=100)

        task_db = progress.add_task("[cyan]Initializing DuckDB...[/]", total=None)
        initialize_database()
        progress.update(task_db, completed=100, total=100)

    console.print()
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        TimeElapsedColumn(),
        console=console,
    ) as progress:
        task_workers = progress.add_task("[cyan]Running initial workers...[/]", total=None)
        run_initial_workers()
        progress.update(task_workers, completed=100, total=100)

    from src.infrastructure.database import DatabaseService

    try:
        db = DatabaseService.get_instance()
        db.persist()
        db.close()
    except RuntimeError:
        pass

    console.print()
    console.print(
        Panel.fit(
            "[bold green]✓ Initialization complete![/]\n\n"
            "  [dim]Review/edit [white]sigmarag.toml[/] as needed\n"
            "  Then run [white]uv run main.py[/] to start the server[/]",
            border_style="green",
        )
    )


def run_defaults() -> None:
    """Non-interactive mode with default configuration (for CI / tests)."""
    from src.infrastructure.database import DatabaseService

    create_data_structure()
    create_config_file()
    clone_or_update_sigma_spec()
    initialize_database()
    run_initial_workers()

    try:
        db = DatabaseService.get_instance()
        db.persist()
        db.close()
    except RuntimeError:
        pass


def main() -> None:
    if "--defaults" in sys.argv[1:]:
        run_defaults()
    else:
        try:
            run_tui()
        except (EOFError, KeyboardInterrupt):
            console.print("\n[yellow]Aborted by user.[/]")
            sys.exit(0)


if __name__ == "__main__":
    main()
