"""Data models for the tool-calling architecture."""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Callable


@dataclass(frozen=True)
class ToolDef:
    """Immutable definition of an available tool.

    Each instance is auto-generated by the :class:`@tool` decorator from
    the function's signature, docstring, and type hints.
    """

    name: str
    description: str
    parameters: dict[str, Any]
    fn: Callable[..., Any]

    def to_json_schema(self) -> dict[str, Any]:
        """Return the OpenAI-compatible tools JSON."""
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": self.parameters,
            },
        }


@dataclass(frozen=True)
class ToolResult:
    """Result of executing a tool."""

    content: str
    tool_call_id: str


class ToolExecutor:
    """Protocol for executing tools by name."""

    async def execute(
        self,
        tool_name: str,
        arguments: dict[str, Any],
        tool_call_id: str,
    ) -> ToolResult: ...


@dataclass
class ToolContext:
    """Shared backend dependencies injected into tool calls."""

    search_engine: Any
    llm_client: Any
    rag_pipeline: Any | None = None


@dataclass
class ToolCall:
    """Parsed tool call from an assistant message."""

    id: str
    name: str
    arguments: dict[str, Any]

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ToolCall:
        """Parse a ``tool_calls`` item from the LLM response."""
        func = data.get("function", {})
        try:
            args = json.loads(func.get("arguments", "{}"))
        except (json.JSONDecodeError, TypeError):
            args = {}
        return cls(
            id=data.get("id", ""),
            name=func.get("name", ""),
            arguments=args,
        )
