"""
Shared utilities and base classes for SigmaHQ RAG application.

This module provides common functionality used across all layers of the application.
"""

# Export exceptions
from .exceptions import (
    AuthenticationError,
    AuthorizationError,
    CacheError,
    ChatError,
    ConfigurationError,
    DatabaseError,
    EmbeddingError,
    FileError,
    LLMError,
    NetworkError,
    RAGError,
    RateLimitError,
    ServiceError,
    SigmaHQError,
    ValidationError,
)

# Export base classes
from .base_service import (
    AsyncComponent,
    AsyncResourceManager,
    BaseService,
    CacheService,
    async_resource_manager,
)

# Export constants
from .constants import (
    APP_DESCRIPTION,
    # Application constants
    APP_NAME,
    APP_VERSION,
    DEFAULT_ALLOWED_FILE_EXTENSIONS,
    DEFAULT_CACHE_ENABLED,
    # Cache configuration
    DEFAULT_CACHE_SIZE,
    DEFAULT_CACHE_TTL,
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_CHUNK_SIZE,
    # Default configuration structure
    DEFAULT_CONFIG,
    DEFAULT_CONVERSATION_HISTORY_LIMIT,
    DEFAULT_DB_MAX_CONNECTIONS,
    # Database configuration
    DEFAULT_DB_PATH,
    DEFAULT_DB_TIMEOUT,
    # RAG configuration
    DEFAULT_EMBEDDING_MODEL,
    # GitHub configuration
    DEFAULT_GITHUB_API_BASE_URL,
    DEFAULT_GITHUB_RATE_LIMIT_DELAY,
    DEFAULT_LLM_API_KEY,
    DEFAULT_LLM_BASE_URL,
    DEFAULT_LLM_ENABLE_STREAMING,
    DEFAULT_LLM_MAX_TOKENS,
    # Default configuration values
    DEFAULT_LLM_MODEL,
    DEFAULT_LLM_TEMPERATURE,
    # LM Studio configuration
    DEFAULT_LM_STUDIO_BASE_URL,
    # File processing configuration
    DEFAULT_MAX_FILE_SIZE_MB,
    DEFAULT_RAG_COLLECTION_NAME,
    DEFAULT_RAG_MIN_SCORE,
    DEFAULT_RAG_N_RESULTS,
    DEFAULT_RAG_PERSIST_DIRECTORY,
    DEFAULT_TEMP_DIR,
    DEFAULT_UPLOAD_DIR,
    ERROR_CODE_AUTHENTICATION_FAILED,
    ERROR_CODE_AUTHORIZATION_FAILED,
    ERROR_CODE_FILE_TOO_LARGE,
    ERROR_CODE_INTERNAL_ERROR,
    ERROR_CODE_RATE_LIMIT_EXCEEDED,
    # Error codes
    ERROR_CODE_SERVICE_UNAVAILABLE,
    ERROR_CODE_TIMEOUT,
    ERROR_CODE_UNSUPPORTED_FILE_TYPE,
    ERROR_CODE_VALIDATION_FAILED,
    SERVICE_CHAT,
    SERVICE_CONFIG,
    SERVICE_DATA,
    SERVICE_DATABASE,
    SERVICE_FILE_PROCESSOR,
    SERVICE_FILE_STORAGE,
    SERVICE_GITHUB,
    # Service names
    SERVICE_LLM,
    SERVICE_LOGGING,
    SERVICE_RAG,
    SERVICE_EMBEDDING,
    SERVICE_APPLICATION,
    STATUS_DEGRADED,
    # Status codes
    STATUS_HEALTHY,
    STATUS_STARTING,
    STATUS_STOPPED,
    STATUS_STOPPING,
    STATUS_UNHEALTHY,
)

# Export types
from .types import (
    # Generic types
    ApiResponse,
    CacheStats,
    ChatCompletionRequest,
    # Chat-related types
    ChatMessage,
    ConversationContext,
    DatabaseConfig,
    # Dataclass types
    DocumentChunk,
    EmbeddingConfig,
    # File processing types
    FileMetadata,
    # Configuration types
    LLMConfig,
    PaginatedResponse,
    ProcessingResult,
    RAGContext,
    # RAG-related types
    RAGResult,
    SearchResult,
    # Service types
    ServiceStatus,
    ValidationResult,
)

# Export utilities
from .utils import (
    async_timer,
    async_to_sync,
    batch_process,
    chunk_text,
    cleanup_temp_files,
    create_directory_if_not_exists,
    create_progress_bar,
    deep_merge,
    flatten_dict,
    format_size,
    generate_hash,
    get_cpu_usage,
    get_current_timestamp,
    get_file_info,
    get_memory_usage,
    get_nested_value,
    get_time_ago,
    handle_service_errors,
    is_valid_email,
    is_valid_url,
    parse_iso_timestamp,
    rate_limit,
    retry_with_backoff,
    safe_divide,
    sanitize_filename,
    set_nested_value,
    sync_to_async,
    timer,
    validate_file_upload,
)

__all__ = [
    # Exceptions
    "SigmaHQError",
    "ConfigurationError", 
    "ServiceError",
    "DatabaseError",
    "RAGError",
    "LLMError",
    "ChatError",
    "ValidationError",
    "CacheError",
    "NetworkError",
    "FileError",
    "AuthenticationError",
    "AuthorizationError",
    "RateLimitError",
    "EmbeddingError",
    
    # Base classes
    "BaseService",
    "AsyncComponent", 
    "CacheService",
    "AsyncResourceManager",
    "async_resource_manager",
    
    # Types
    "ChatMessage",
    "ChatCompletionRequest",
    "RAGResult",
    "RAGContext",
    "LLMConfig",
    "EmbeddingConfig",
    "DatabaseConfig",
    "ServiceStatus",
    "CacheStats",
    "FileMetadata",
    "ProcessingResult",
    "ApiResponse",
    "PaginatedResponse",
    "ValidationResult",
    "DocumentChunk",
    "SearchResult",
    "ConversationContext",
    
    # Utilities
    "handle_service_errors",
    "retry_with_backoff",
    "rate_limit",
    "async_to_sync",
    "sync_to_async",
    "timer",
    "async_timer",
    "generate_hash",
    "sanitize_filename",
    "validate_file_upload",
    "chunk_text",
    "format_size",
    "get_file_info",
    "create_directory_if_not_exists",
    "safe_divide",
    "get_nested_value",
    "set_nested_value",
    "deep_merge",
    "flatten_dict",
    "is_valid_email",
    "is_valid_url",
    "get_current_timestamp",
    "parse_iso_timestamp",
    "get_time_ago",
    "create_progress_bar",
    "batch_process",
    "get_memory_usage",
    "get_cpu_usage",
    "cleanup_temp_files",
    
    # Constants
    "APP_NAME",
    "APP_VERSION", 
    "APP_DESCRIPTION",
    "DEFAULT_LLM_MODEL",
    "DEFAULT_LLM_BASE_URL",
    "DEFAULT_LLM_API_KEY",
    "DEFAULT_LLM_TEMPERATURE",
    "DEFAULT_LLM_MAX_TOKENS",
    "DEFAULT_LLM_ENABLE_STREAMING",
    "DEFAULT_CONVERSATION_HISTORY_LIMIT",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_RAG_N_RESULTS",
    "DEFAULT_RAG_MIN_SCORE",
    "DEFAULT_RAG_COLLECTION_NAME",
    "DEFAULT_RAG_PERSIST_DIRECTORY",
    "DEFAULT_DB_PATH",
    "DEFAULT_DB_MAX_CONNECTIONS",
    "DEFAULT_DB_TIMEOUT",
    "DEFAULT_CACHE_SIZE",
    "DEFAULT_CACHE_TTL",
    "DEFAULT_CACHE_ENABLED",
    "DEFAULT_ALLOWED_FILE_EXTENSIONS",
    "SERVICE_LLM",
    "SERVICE_RAG",
    "SERVICE_CHAT",
    "SERVICE_DATA",
    "SERVICE_CONFIG",
    "SERVICE_LOGGING",
    "SERVICE_DATABASE",
    "SERVICE_FILE_PROCESSOR",
    "SERVICE_FILE_STORAGE",
    "SERVICE_GITHUB",
    "SERVICE_LM_STUDIO",
    "SERVICE_EMBEDDING",
    "DEFAULT_GITHUB_API_BASE_URL",
    "DEFAULT_GITHUB_RATE_LIMIT_DELAY",
    "ERROR_CODE_SERVICE_UNAVAILABLE",
    "ERROR_CODE_VALIDATION_FAILED",
    "ERROR_CODE_FILE_TOO_LARGE",
    "ERROR_CODE_UNSUPPORTED_FILE_TYPE",
    "ERROR_CODE_RATE_LIMIT_EXCEEDED",
    "ERROR_CODE_TIMEOUT",
    "ERROR_CODE_AUTHENTICATION_FAILED",
    "ERROR_CODE_AUTHORIZATION_FAILED",
    "ERROR_CODE_INTERNAL_ERROR",
    "STATUS_HEALTHY",
    "STATUS_UNHEALTHY",
    "STATUS_DEGRADED",
    "STATUS_STARTING",
    "STATUS_STOPPING",
    "STATUS_STOPPED",
    "DEFAULT_CONFIG",
]